spring:
  kafka:
    bootstrap:
      servers: localhost:9092
    producer:
      key-serializer: your-key-serializer
      value-serializer: your-value-serializer
    consumer:
      group-id: your-group-id
    properties:
      num:
        partitions: 3
        replication:
          factor: 3