spring:
  kafka:
    bootstrap:
      servers: kafka_broker:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      security:
        protocol: SSL
        ssl:
          key-store-location: /path/to/keystore.jks
          key-store-password: keystore_password
          key-password: key_password
          trust-store-location: /path/to/truststore.jks
          trust-store-password: truststore_password
    consumer:
      group-id: your-group-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      security:
        protocol: SSL
        ssl:
          key-store-location: /path/to/keystore.jks
          key-store-password: keystore_password
          key-password: key_password
          trust-store-location: /path/to/truststore.jks
          trust-store-password: truststore_password
    properties:
      num:
        partitions: 3
        replication:
          factor: 3