# Use the official node 16 image as the base image
FROM node:16

# Install cron and any other necessary utilities
RUN apt-get update && apt-get -y install cron

# Add the cron job file
ADD cron-job /etc/cron.d/cron-job

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/cron-job

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Add a shell script as the entry point
ADD entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set the shell script as the entry point
ENTRYPOINT ["/entrypoint.sh"]