apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/yourusername/log  # Replace with the path to the directory on your Mac

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-volume-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: log