apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekswebapp
spec:
  selector:
    matchLabels:
      app: ekswebapp
  template:
    metadata:
      labels:
        app: ekswebapp
    spec:
      containers:
        - name: ekswebapp
          image: 334105551007.dkr.ecr.us-east-2.amazonaws.com/ekswebapp
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: tcp
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ekswebapp
spec:
  selector:
    app: ekswebapp
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer