# Use the official Node.js 16 image
FROM node:16

# Create necessary directories and set permissions
RUN mkdir -p /app/log /app/certs
RUN chmod -R 777 /app/certs
RUN chmod -R 777 /app/log

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json .npmrc /app/
COPY startup.sh /app/startup.sh
RUN npm install -g npm@9.7.1
RUN npm install --force
COPY . /app

# Set permissions and expose port
RUN chmod 777 /app/load-env.sh
RUN chmod +x /app/startup.sh
EXPOSE 3000

# Start the application
USER node
ENTRYPOINT ["/app/startup.sh"]