# Use the official Node.js 16 image
FROM node:16

# Update package repositories and install logrotate and cron
USER root
RUN apt-get update && apt-get install -y logrotate cron

# Create necessary directories and set permissions
RUN mkdir -p /app/log /app/certs

# Set the working directory
WORKDIR /app

COPY package.json package-lock.json .npmrc /app/
COPY startup.sh /app/startup.sh
COPY logify.sh /app/logify.sh

RUN npm install -g npm@9.7.1
RUN npm install --force

COPY . /app

RUN ls /app/

RUN chmod -R 777 /app/certs
RUN chmod -R 777 /app/log
RUN chmod 777 /app/load-env.sh
RUN chmod +x /app/startup.sh

EXPOSE 3000

RUN chmod -R 755 /app/log
RUN touch /app/log/formio.log && chmod 664 /app/log/formio.log

RUN touch /var/log/cron.log
ADD logrotate.conf /etc/logrotate.conf
ADD logrotate-cron /etc/logrotate-cron
RUN chmod 0644 /etc/cron.d/logrotate-cron
RUN crontab /etc/cron.d/lorotate-cron
RUN chmod -R 777 logify.sh && chmod +x logify.sh


USER node
ENTRYPOINT ["bin/sh", "-c" , "/app/startup.sh"]