apiVersion: apps/v1
kind: Deployment
metadata:
  name: formio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formio
  template:
    metadata:
      labels:
        app: formio
    spec:
      containers:
        - name: formio-container
          image: temprk/temp_repo_local:logrotate11
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: app-volume
              mountPath: /app
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: app-volume
          emptyDir: {}