#version: '3'
#
#services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: wurstmeister/kafka
#    container_name: kafka
#    ports:
#      - "9092:9092"
#      - "9093:9093"
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:SSL,OUTSIDE:PLAINTEXT
#      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
#      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#      KAFKA_CREATE_TOPICS: "inBoundNotifq:3:3"
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/keystore.jks"
#      KAFKA_SSL_KEYSTORE_PASSWORD: "password"
#      KAFKA_SSL_KEY_PASSWORD: "password"
#      KAFKA_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/truststore.jks"
#      KAFKA_SSL_TRUSTSTORE_PASSWORD: "password"
#      KAFKA_OPTS: "-Djavax.net.debug=ssl"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /tmp/keystore.jks:/etc/kafka/secrets/keystore.jks
#      - /tmp/truststore.jks:/etc/kafka/secrets/truststore.jks