#version: '3'
#
#services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: wurstmeister/kafka
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:SSL,OUTSIDE:PLAINTEXT
#      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
#      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#      KAFKA_CREATE_TOPICS: "inBoundNotifq:3:2"
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /Users/rishikeshkhire/Documents/workspace/Java/proj1/src/main/resources/kafkaDockerfile/ssl/keystore.jks:/etc/kafka/secrets/keystore.jks
#      - /Users/rishikeshkhire/Documents/workspace/Java/proj1/src/main/resources/kafkaDockerfile/ssl/truststore.jks:/etc/kafka/secrets/truststore.jks
#    command:
#      - start-kafka.sh
#      - bash
#      - -c
#      - |
#        export KAFKA_OPTS="-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"
#        export KAFKA_OPTS="$KAFKA_OPTS -Djava.security.krb5.conf=/etc/kafka/secrets/krb5.conf"
#        export KAFKA_OPTS="$KAFKA_OPTS -Djavax.net.ssl.keyStore=/etc/kafka/secrets/keystore.jks"
#        export KAFKA_OPTS="$KAFKA_OPTS -Djavax.net.ssl.keyStorePassword=password"
#        export KAFKA_OPTS="$KAFKA_OPTS -Djavax.net.ssl.trustStore=/etc/kafka/secrets/truststore.jks"
#        export KAFKA_OPTS="$KAFKA_OPTS -Djavax.net.ssl.trustStorePassword=password"
#        export KAFKA_OPTS="$KAFKA_OPTS -Djavax.net.debug=ssl"
#        export KAFKA_OPTS="$KAFKA_OPTS -Djavax.net.ssl.keyAlgorithm=RSA"
#        export KAFKA_OPTS="$KAFKA_OPTS -Djavax.net.ssl.trustAlgorithm=SunX509"
#        export KAFKA_OPTS="$KAFKA_OPTS -Djavax.net.ssl.protocol=TLS"