package Exception;

public enum EFormsErrorCode {

    EFORM_GENERIC_ERROR,
    EFORMS_INTERNAL_ERROR,
    EFORMS_VALIDATION_ERROR,
    EFORMS_AUTHENTICATION_ERROR,
    EFORMS_AUTHORIZATION_ERROR,
    EFORMS_FORBIDDEN_ERROR,
    EFORMS_NOT_FOUND_ERROR,
    EFORMS_METHOD_NOT_ALLOWED_ERROR,
    EFORMS_NOT_ACCEPTABLE_ERROR,
    EFORMS_UNAUTHORIZED_ERROR,
    EFORMS_TENANT_NOT_FOUND,
    EFORMS_GENERIC_ERROR,
    EFORMS_FORMNAME_NOT_FOUND,
    EFORMS_TEMPLATE_NOT_FOUND

}
